### ISSUE TITLE
panic checkers module is not defined

### ISSUE THREAD

**Issue by samlaf** [cosmosregistry/chain-minimal#120]
Following the tutorial at https://tutorials.cosmos.network/hands-on-exercise/0-native/2-build-module.html

I've tried simply cloning `chain-minimal` and `minimal-module-example`, and then pointing chain-minimal to minimal-module-example, and when running
```
go mod tidy
make install
make init
minid start
```

I get
```
panic: all modules must be defined when setting SetOrderInitGenesis, missing: [checkers]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/module.(*Manager).assertNoForgottenModules(0x14000c37a00, {0x10666878e, 0x13}, {0x1400092ce00, 0x5, 0x140011f9860?}, 0x1400110f148)
        /Users/samlaf/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.3/types/module/module.go:634 +0x2dc
github.com/cosmos/cosmos-sdk/types/module.(*Manager).SetOrderInitGenesis(0x14000c37a00, {0x1400092ce00, 0x5, 0x8})
        /Users/samlaf/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.3/types/module/module.go:347 +0x5c
github.com/cosmos/cosmos-sdk/runtime.(*App).Load(0x14000b3ee70, 0x1)
        /Users/samlaf/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.3/runtime/app.go:105 +0x44
github.com/cosmosregistry/chain-minimal/app.NewMiniApp({0x1075648c8?, 0x140003c8bd0}, {0x107573e98, 0x140001860e0}, {0x0, 0x0}, 0x88?, {0x107539180?, 0x14000c3ec40}, {0x0, ...})
        /Users/samlaf/devel/cosmos/chain-minimal/app/app.go:152 +0x638
github.com/cosmosregistry/chain-minimal/cmd/minid/cmd.appExport({0x1075648c8, 0x140003c8bd0}, {0x107573e98, 0x140001860e0}, {0x0, 0x0}, 0xffffffffffffffff, 0x68?, {0x108886360, 0x0, ...}, ...)
        /Users/samlaf/devel/cosmos/chain-minimal/cmd/minid/cmd/commands.go:154 +0x24c
github.com/cosmos/cosmos-sdk/server.ExportCmd.func1(0x1400063ca00?, {0x108886360?, 0x0?, 0x0?})
        /Users/samlaf/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.3/server/export.go:81 +0x494
github.com/spf13/cobra.(*Command).execute(0x1400093e600, {0x108886360, 0x0, 0x0})
        /Users/samlaf/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x140008f8000)
        /Users/samlaf/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/samlaf/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/samlaf/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1400008c6e8?, {0x0, 0x0}, {0x14000baeaf8, 0x14})
        /Users/samlaf/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.3/server/cmd/execute.go:34 +0x154
main.main()
        /Users/samlaf/devel/cosmos/chain-minimal/cmd/minid/main.go:18 +0x40
```

**Comment by julienrbrt** [comment]
Hi!

This means you have forgotten to add wire the module here: https://github.com/cosmosregistry/chain-minimal/blob/1591ff7/app/app.yaml#L13
